server.port=9071
# wildfly standalone xml connectivity
#spring.datasource.jndi-name=java:jboss/track_cpool
#spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

#local
spring.datasource.url=jdbc:sqlserver://localhost:50050;databaseName=IBA13012026
spring.datasource.username=sa
spring.datasource.password=kumaran

#uae-test server
#spring.datasource.url=jdbc:sqlserver://v-softtech.database.windows.net:1433;databaseName=scan2track-test-1.0-uae-1
#spring.datasource.username=track@v-softtech
#spring.datasource.password=^Tr5ck@!23

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServer2012Dialect
#
## Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = none
spring.jpa.properties.hibernate.ejb.interceptor = com.integration.general.helpers.configs.HibernateInterceptor
spring.jpa.hibernate.naming.implicit-strategy = org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy = org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.multiTenant.prefix=##plant##
spring.credential.login-path=/api/login,/api/refresh,/api/ping
spring.credential.swagger-path=/v2/api-docs,/configuration/ui\
  ,/swagger-resources/**,/configuration/security,/swagger-ui.html,/webjars/**
spring.credential.security-check = false
spring.swagger.base-path=com.integration.general
#spring.crypto.key-path=E:/sts/key/des.key
#spring.crypto.key-path=/home/abdul/project/accounts/working/des.key
spring.crypto.key-path=/des.key

spring.jwtutil.secretKey=uclo-generate-key
##1 hour
spring.jwtutil.tokenValidity =  3600
##30 days
spring.jwtutil.refreshTokenValidity =  2592000

spring.date.time.zone = GMT+5:30
spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss
spring.mvc.format.time=HH:mm:ss

spring.date.time.dateTimeFormatInFile = yyyy-MM-dd_hh-mm-ss
spring.date.time.sql-code = 104

spring.base.path=/api
useSwagger=true

#600000 10 minutes
spring.datasource.hikari.maxLifeTime : 500000

#spring boot log
logging.level.root = FATAL
logging.level.com.integration.general = TRACE
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=false
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=OFF
